# filepath: .github/workflows/run-notion-automation.yml
name: Run Notion Automation

on:
  schedule:
    # Run every Sunday at 23:59
    - cron: "20 13 * * 0"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the script
      - name: Run Notion Automation
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python notion_automation/notion_automation.py

      # Upload log file as an artifact
      - name: Upload log file
        uses: actions/upload-artifact@v3.1.2
        with:
          name: notion-automation-log
          path: notion_automation/notion_automation.log
          retention-days: 30
